name: Repo checkout test

on: push

jobs:
    my-test-job:
        runs-on: ubuntu-latest
        name: A job to checkout and verify our repo files are present
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Checking our repository
              uses: ./
            - name: Checking environment variables
              uses: ./
              with:
                entrypoint: envtest.sh

              #uses: MeterianHQ/meterian-github-action@action-update
              #with:
                #entrypoint: /test_entrypoint.sh
            # - name: Workspace test
            #   uses: MeterianHQ/meterian-github-action@action-update
            #   with:
            #     entrypoint: /bin/bash
            #     args: -al