name: scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with dockerized Meterian client
            uses: MeterianHQ/meterian-github-action@entrypoint-scripts-update
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                args: --min-security=85
