name: Test

on: push

jobs:
    my-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Path test
              uses: MeterianHQ/meterian-github-action@action-update
              with:
                entrypoint: /entrypoint.sh
            # - name: Workspace test
            #   uses: MeterianHQ/meterian-github-action@action-update
            #   with:
            #     entrypoint: /bin/bash
            #     args: -al